# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100)),
                ('bldg', models.CharField(blank=True, max_length=50, null=True)),
                ('streets', models.CharField(blank=True, max_length=50, null=True)),
                ('town', models.CharField(max_length=50)),
                ('city', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('trade_name', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_type', models.IntegerField(choices=[(1, 'Person'), (2, 'Artificial')], default=1)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_num', models.CharField(blank=True, max_length=20, null=True)),
                ('ss_num', models.CharField(blank=True, max_length=20, null=True)),
                ('health_num', models.CharField(blank=True, max_length=20, null=True)),
                ('hdmf_num', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField()),
                ('line_of_business', models.IntegerField(blank=True, choices=[(1, 'OTHER TELECOMMUNICATION')], null=True)),
                ('is_client', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.IntegerField(choices=[(1, 'Telephone'), (2, 'Mobile')], default=1)),
                ('number', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
        ),
    ]
