# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='line_of_business',
        ),
    ]
