# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
