# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, choices=[('1', 'CDO'), ('2', 'CEB'), ('3', 'MNL')], max_length=5, null=True),
        ),
    ]
