# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20171116_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='alias',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='tax_num',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='person',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='contact person'),
        ),
    ]
