# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_contact_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tax_num',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
