# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20171118_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='vip_alias',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tax_num',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
