# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0011_auto_20171118_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('cpd_units', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reg_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('resource_persons', models.ManyToManyField(to='contacts.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pay_type', models.IntegerField(choices=[(1, 'cash'), (2, 'check')])),
                ('check_date', models.DateField()),
                ('check_bank', models.CharField(max_length=10)),
                ('payor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Organizer')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_class', models.IntegerField(blank=True, choices=[(1, 'Membership Fee'), (1, 'Seminar Fee')], null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField(default=django.utils.timezone.now)),
                ('time_in_1', models.TimeField()),
                ('time_start', models.TimeField()),
                ('is_present', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sched_date', models.DateField(verbose_name=django.utils.timezone.now)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('description', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='event_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Schedule'),
        ),
        migrations.AddField(
            model_name='registration',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Registration'),
        ),
    ]
