# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('contacts', '0001_initial'),
        ('bir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirCompliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('bir_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bir.BirForm')),
            ],
            options={
                'verbose_name_plural': 'BirCompliance',
            },
        ),
        migrations.CreateModel(
            name='BirDeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('year', models.IntegerField()),
                ('date_notify_start', models.DateField()),
                ('compliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.BirCompliance')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(default=django.utils.timezone.now)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPractitioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(default=django.utils.timezone.now)),
                ('date_transferred', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.Client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='DeadlineStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Working'), (3, 'Done'), (4, 'Filing'), (5, 'Verifying'), (6, 'Paid'), (7, 'Done')], default=1)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('bir_deadline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.BirDeadline')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='practitioners',
            field=models.ManyToManyField(through='compliance.ClientPractitioner', to='employees.Employee'),
        ),
        migrations.AddField(
            model_name='client',
            name='rdo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bir.Rdo'),
        ),
        migrations.AddField(
            model_name='bircompliance',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.Client'),
        ),
    ]
