# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='line_of_business',
            field=models.IntegerField(blank=True, choices=[(1, 'OTHER TELECOMMUNICATION')], null=True),
        ),
    ]
