# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_client_line_of_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpractitioner',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact', verbose_name='client'),
        ),
    ]
