# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_auto_20171103_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bircompliance',
            options={'verbose_name_plural': 'Compliance - BIR'},
        ),
        migrations.AlterModelOptions(
            name='birdeadline',
            options={'verbose_name_plural': 'Deadlines - BIR'},
        ),
        migrations.AlterModelOptions(
            name='clientpractitioner',
            options={'verbose_name': 'Practitioner'},
        ),
        migrations.RemoveField(
            model_name='birdeadline',
            name='day',
        ),
        migrations.RemoveField(
            model_name='birdeadline',
            name='month',
        ),
        migrations.RemoveField(
            model_name='birdeadline',
            name='year',
        ),
        migrations.AddField(
            model_name='birdeadline',
            name='date_deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
