# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_auto_20171103_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deadlinestatus',
            options={'verbose_name_plural': 'Deadline Status'},
        ),
        migrations.AlterField(
            model_name='birdeadline',
            name='date_deadline',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='birdeadline',
            name='date_notify_start',
            field=models.DateField(verbose_name='notify starting'),
        ),
        migrations.AlterField(
            model_name='client',
            name='line_of_business',
            field=models.IntegerField(blank=True, choices=[(1, 'OTHER TELECOMMUNICATION'), (2, 'OTHER WHOLESALING'), (3, 'SALE OF AGGREGATES'), (4, 'OTHER RETAIL SALE IN SPECIALIZED STORES')], null=True),
        ),
    ]
