# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_auto_20171114_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdeadline',
            name='date_notify_start',
            field=models.DateField(verbose_name='notification starts on'),
        ),
    ]
