# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0007_client_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='engagement_series_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientpractitioner',
            name='date_assigned',
            field=models.DateField(),
        ),
    ]
