# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0008_auto_20171118_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='engagement_series_num',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
