# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0009_auto_20171118_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientpractitioner',
            options={'ordering': ['-date_assigned'], 'verbose_name': 'Practitioner'},
        ),
        migrations.AddField(
            model_name='deadlinestatus',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deadlinestatus',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deadlinestatus',
            name='status',
            field=models.IntegerField(choices=[(1, 'Working'), (2, 'Drafted'), (3, 'Filing'), (4, 'Verification'), (5, 'Paid'), (6, 'Done')], default=1),
        ),
    ]
