# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0011_auto_20171125_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdeadline',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='birdeadline',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bircompliance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='engagement_series_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
