# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0012_auto_20171125_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadlinestatus',
            name='status',
            field=models.IntegerField(choices=[(1, 'Working'), (2, 'Draft'), (3, 'Filing'), (4, 'Verification'), (5, 'Payment'), (6, 'Done'), (7, 'Archive')], default=1),
        ),
    ]
