# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 02:20
from __future__ import unicode_literals

import compliance.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0013_auto_20171128_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('attachment', models.FileField(upload_to=compliance.models.client_directory_path)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='compliance.Client')),
            ],
        ),
    ]
