# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0015_auto_20171128_1053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientAttachments',
            new_name='ClientAttachment',
        ),
    ]
