# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costcenters', '0002_auto_20171130_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='costcenters.Branch'),
        ),
    ]
