# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costcenters', '0003_auto_20171130_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
        ),
    ]
