# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costcenters', '0004_auto_20171130_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
        ),
        migrations.AlterField(
            model_name='project',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='costcenters.Branch'),
        ),
        migrations.AlterField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_projects', to='costcenters.Project'),
        ),
    ]
