# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcenters', '0005_auto_20171130_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
