# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20171206_1655'),
        ('employees', '0012_auto_20171202_1145'),
        ('costcenters', '0006_auto_20171130_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('holiday', models.CharField(max_length=50)),
                ('holiday_type', models.IntegerField(choices=[(1, 'Regular'), (2, 'Special'), (3, 'Special Working'), (4, 'Others')])),
                ('pay_on_rest', models.IntegerField(default=100)),
                ('pay_on_absent', models.IntegerField(default=100)),
                ('pay_premium_normal', models.IntegerField(default=100)),
                ('ot_premium_normal', models.IntegerField(default=30)),
                ('pay_premium_rest', models.IntegerField(default=160)),
                ('ot_premium_rest', models.IntegerField(default=48)),
                ('cities', models.ManyToManyField(to='public.City')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='public.City'),
        ),
        migrations.AddField(
            model_name='branch',
            name='employees',
            field=models.ManyToManyField(null=True, to='employees.Employee'),
        ),
    ]
