# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcenters', '0007_auto_20171206_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='employees',
            field=models.ManyToManyField(to='employees.Employee'),
        ),
    ]
