# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcenters', '0008_auto_20171206_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='pay_on_rest',
        ),
        migrations.AddField(
            model_name='holiday',
            name='cola_premium_normal',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='ot_premium_normal',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='ot_premium_rest',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='pay_premium_rest',
            field=models.IntegerField(default=60),
        ),
    ]
