# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('abbr', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('date_hired', models.DateField()),
                ('date_resigned', models.DateField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact', verbose_name='Name')),
            ],
        ),
    ]
