# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 14:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_hired',
            field=models.DateField(default=datetime.datetime(2017, 11, 17, 14, 4, 57, 242666, tzinfo=utc)),
        ),
    ]
