# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 01:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20171117_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_hired',
            field=models.DateField(default=datetime.datetime(2017, 11, 18, 1, 4, 36, 247261, tzinfo=utc)),
        ),
    ]
