# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 01:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20171118_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_hired',
            field=models.DateField(default=datetime.datetime(2017, 11, 18, 1, 16, 39, 186196, tzinfo=utc)),
        ),
    ]
