# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20171118_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_hired',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
