# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0008_auto_20171118_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='supervisors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sups', to='employees.Employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
