# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20171129_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(default=django.utils.timezone.now)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('payroll_type', models.IntegerField(choices=[(1, 'Daily'), (2, 'Periodic')], default=2, max_length=2)),
                ('monthly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee', verbose_name='Name')),
            ],
        ),
    ]
