# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='payroll_type',
            field=models.IntegerField(choices=[(1, 'Daily'), (2, 'Periodic')], default=2),
        ),
    ]
