# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_code', models.CharField(max_length=10)),
                ('form', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('deadline_period', models.IntegerField(choices=[(1, 'monthly'), (2, 'quarterly'), (3, 'annually'), (4, 'custom')])),
                ('deadline_cy_ref', models.IntegerField(choices=[(1, 'absolute'), (2, 'relative')])),
                ('deadline_date_type', models.IntegerField(choices=[(1, 'fix'), (2, 'count')])),
            ],
        ),
        migrations.CreateModel(
            name='BirFormSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('bir_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bir.BirForm')),
            ],
        ),
        migrations.CreateModel(
            name='Rdo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=3)),
                ('rdo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
