# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birform',
            name='deadline_cy_ref',
            field=models.IntegerField(choices=[(1, 'absolute'), (2, 'relative')], default=2, verbose_name='bus. year ref'),
        ),
        migrations.AlterField(
            model_name='birform',
            name='deadline_date_type',
            field=models.IntegerField(choices=[(1, 'fix'), (2, 'count')], default=1, verbose_name='date type'),
        ),
        migrations.AlterField(
            model_name='birform',
            name='deadline_period',
            field=models.IntegerField(choices=[(1, 'monthly'), (2, 'quarterly'), (3, 'annually'), (4, 'custom')], verbose_name='period'),
        ),
        migrations.AlterField(
            model_name='birform',
            name='form_code',
            field=models.CharField(max_length=10, verbose_name='code'),
        ),
    ]
