# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 03:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0012_auto_20171202_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave', models.IntegerField(choices=[(1, 'sl'), (2, 'vl'), (3, 'sil'), (4, 'ml'), (5, 'pyl'), (6, 'pll')])),
                ('date', models.DateField()),
                ('hours', models.PositiveIntegerField(default=8, validators=[django.core.validators.MaxValueValidator(24)])),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Issuance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave', models.IntegerField(choices=[(1, 'sl'), (2, 'vl'), (3, 'sil'), (4, 'ml'), (5, 'pyl'), (6, 'pll')])),
                ('hours', models.PositiveIntegerField(default=0)),
                ('valid_from_date', models.DateField(default=django.utils.timezone.now, verbose_name='From')),
                ('valid_until_date', models.DateField(verbose_name='Until')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
        ),
    ]
