# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 13:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='hours',
        ),
        migrations.AddField(
            model_name='application',
            name='paid_hours',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(24)]),
        ),
    ]
