# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 14:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_auto_20171207_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuance',
            name='valid_from_date',
        ),
        migrations.RemoveField(
            model_name='issuance',
            name='valid_until_date',
        ),
        migrations.AddField(
            model_name='application',
            name='charge_to_issuances',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='issuance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='issuance',
            name='valid_on_year',
            field=models.IntegerField(choices=[(2016, 2016), (2017, 2017), (2018, 2018)], default=2017, verbose_name='From'),
        ),
    ]
