# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_auto_20171207_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuance',
            name='valid_on_year',
            field=models.IntegerField(choices=[(2016, 2016), (2017, 2017), (2018, 2018)], null=True, verbose_name='From'),
        ),
    ]
