# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_auto_20171207_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuance',
            name='valid_on_year',
            field=models.IntegerField(choices=[(2017, 2017), (2018, 2018)], null=True),
        ),
    ]
