# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=50, verbose_name='city/municipality')),
                ('city_class', models.IntegerField(choices=[(1, 'cc'), (2, 'huc'), (3, 'icc'), (4, 'municipality')])),
            ],
            options={
                'verbose_name_plural': 'Cities/Municipalities',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_type', models.IntegerField(choices=[(1, 'Regular'), (2, 'Special'), (3, 'Others')])),
                ('date', models.DateField()),
                ('holiday', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.City')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=5)),
                ('province', models.CharField(max_length=50, verbose_name='province')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Province'),
        ),
    ]
