# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='alias',
            field=models.CharField(max_length=20),
        ),
    ]
