# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20171202_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='city',
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
