# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costcenters', '0001_initial'),
        ('employees', '0010_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
            options={
                'verbose_name_plural': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_date_time_in', models.DateTimeField(blank=True, null=True)),
                ('final_date_time_out', models.DateTimeField(blank=True, null=True)),
                ('minutes_late_in', models.IntegerField(default=0)),
                ('minutes_early_out', models.IntegerField(default=0)),
                ('minutes_night_premium', models.IntegerField(default=0)),
                ('minutes_ot_premium', models.IntegerField(default=0)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtr.Attendance')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('log_type', models.CharField(choices=[('na', 'None'), ('in', 'In'), ('ou', 'Out'), ('oti', 'Overtime - In'), ('oto', 'Overtime - Out')], default='NA', max_length=3)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_rest_day', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_threshold_early_in', models.IntegerField(default=0)),
                ('minutes_threshold_late_in', models.IntegerField(default=0)),
                ('minutes_threshold_early_out', models.IntegerField(default=0)),
                ('minutes_threshold_late_out', models.IntegerField(default=0)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtr.Schedule')),
                ('sub_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='costcenters.SubProject', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.TimeField(verbose_name='In')),
                ('time_out', models.TimeField(verbose_name='Out')),
                ('hours_npb', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Non-paid Break')),
                ('hours_scheduled', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Scheduled')),
                ('hours_paid', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Paid')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('is_ot', models.BooleanField(default=False, verbose_name='OT')),
            ],
        ),
        migrations.AddField(
            model_name='scheduletimetable',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtr.Timetable'),
        ),
        migrations.AddField(
            model_name='scheduletimetable',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='costcenters.Work', verbose_name='Scope of work'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='timetables',
            field=models.ManyToManyField(through='dtr.ScheduleTimetable', to='dtr.Timetable'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='schedule_timetable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dtr.ScheduleTimetable'),
        ),
    ]
