# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletimetable',
            name='sub_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='costcenters.Project', verbose_name='Project'),
        ),
    ]
