# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtr', '0002_auto_20171130_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='timetables',
            new_name='timetable',
        ),
    ]
