# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtr', '0004_auto_20171201_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='timetables',
        ),
    ]
