# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtr', '0005_remove_schedule_timetables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_type',
            field=models.CharField(choices=[(1, 'None'), (2, 'In'), (3, 'Out'), (4, 'Overtime - In'), (5, 'Overtime - Out')], default='NA', max_length=3),
        ),
        migrations.AlterField(
            model_name='scheduletimetable',
            name='minutes_threshold_early_in',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='scheduletimetable',
            name='minutes_threshold_early_out',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='scheduletimetable',
            name='minutes_threshold_late_in',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='scheduletimetable',
            name='minutes_threshold_late_out',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
