# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtr', '0007_auto_20171201_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
    ]
