# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtr', '0008_attendancelog_is_absent'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
