# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 08:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtr', '0009_log_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
