# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtr', '0010_auto_20171205_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraceLateIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grace_type', models.IntegerField(choices=[(1, 'instance'), (2, 'periodic')], default=1)),
                ('grace_sub_type', models.IntegerField(blank=True, choices=[(1, 'daily'), (2, 'monthly')], default=None, null=True)),
                ('value_minutes', models.IntegerField(default=0)),
                ('value_type', models.IntegerField(choices=[(1, 'simple'), (2, 'complex')], default=1)),
                ('alias', models.CharField(max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='timetable',
            name='grace_late_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dtr.GraceLateIn'),
        ),
    ]
