# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtr', '0011_auto_20171206_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='minutes_late_in_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timetable',
            name='is_timein_nextday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timetable',
            name='is_timeout_nextday',
            field=models.BooleanField(default=False),
        ),
    ]
