# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtr', '0012_auto_20171206_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='with_deduction',
            field=models.BooleanField(default=True),
        ),
    ]
