# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_auto_20171207_1314'),
        ('dtr', '0013_attendancelog_with_deduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelog',
            name='with_deduction',
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaves.Application'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='hours_deducted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='hours_paid',
            field=models.IntegerField(default=0),
        ),
    ]
