# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtr', '0014_auto_20171207_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='is_rest_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='hours_npb',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Non-paid Break'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='hours_paid',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Paid'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='hours_scheduled',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Scheduled'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time_in',
            field=models.TimeField(null=True, verbose_name='In'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time_out',
            field=models.TimeField(null=True, verbose_name='Out'),
        ),
    ]
